#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

# build Apache Thrift on Travis CI - https://travis-ci.org/

sudo: required
dist: trusty

services:
  - docker

script:
  - ./bootstrap.sh
  - ./configure --prefix=/usr/local/ --with-cpp --with-go --without-dart --without-haskell --without-java --without-lua --without-nodejs --without-perl --without-php --without-php_extension --without-python --without-ruby --without-erlang
  - make

env:
  global:
    - TEST_NAME=""
    - BUILD_CMD="none"
    - BUILD_ARG=""
    - BUILD_ENV="-e CC=clang -e CXX=clang++"
    - DISTRO=ubuntu
    - BUILD_LIBS="CPP C_GLIB HASKELL JAVA PYTHON TESTING TUTORIALS"  # only meaningful for CMake builds

deploy:
  provider: releases
  api_key:
    secure: x4v8iywUNK254dVGZEpUc2F+8HoB5Sn/b5WZNtR6+z5xeVr+10w9iZcv14MPGepxJgJ+36Hqzqqk3HpKnU6DcweiebHVtGgxkTPzaADZU4s/jwdoEXIGb+W9rDSM9AYr3KcgdMc5bW69U4xHv2z9I73yOCcMcojAv3jowUohoXSIscbj5uekKkGjgjSoQPyUvz2pS8NxQ8+55I3alT6ZJ2mD5/HrgXf8VjW+j50DkOvwMlPQX8g8LkCXs8c/daxV9HJxojUlZJyAHF7YgWYq9YviPRuNkC+Ltt1QAIJRm6ujgfD4VL6csa04lWCbPMarzpubpGGJuya+vEyDPgOrQa7oEmkLa6OiOWTTUW4oZhxAjVh6B/sobSbvbTvUvyY4axVMVgE9jibhLMoUoiv58QfrywAWZjCoSIgghGFh60N/WczV/jN1hTIwsa6qHMnTYtsLOhiH16MdC95mcDNOYjJk41RScha8T2g1RkdxKYAhsKPNQNwAgVwDU+WlsotXFL8sQlR4hs/XP0gem432Pll8Iz9EeMVCSKlhbC/3+3nH73ebMibJS65OoLWHao3iX66ntG98q7DJzjsBMwLubki+bJWPT0+sb3Y5kLE1MAsE+8o3tf0VV42ErrxyHJLM+PalnZ/JQzwhfs+hsOIdcdHqAofZyF4ybBO3XAFHR3k=
  file: "./compiler/cpp/thrift"
  on:
    repo: karlmutch/thrift
    branch: dev
